### ISSUE TITLE
Installation failed - Akeneo 1.4.9

### ISSUE THREAD

**Issue by rskonieczka** [linslin/AdvancedConnectorBundle#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oro/platform 1.0.0-beta17 requires sensio/generator-bundle 2.3.4 -> no matching package found.
    - Can only install one of: akeneo/pim-community-dev[1.3.x-dev, 1.4.x-dev].
    - Can only install one of: akeneo/pim-community-dev[1.4.x-dev, 1.3.x-dev].
    - Can only install one of: akeneo/pim-community-dev[1.4.x-dev, 1.3.x-dev].
    - linslin/advanced-connector-bundle 0.1.0 requires akeneo/pim-community-dev ~1.2@stable,<1.4 -> satisfiable by akeneo/pim-community-dev[1.2.x-dev, 1.3.x-dev].
    - akeneo/pim-community-dev 1.2.x-dev requires oro/platform 1.0.0-beta17 -> satisfiable by oro/platform[1.0.0-beta17].
    - Installation request for linslin/advanced-connector-bundle ^0.1.0 -> satisfiable by linslin/advanced-connector-bundle[0.1.0].
    - Installation request for akeneo/pim-community-dev == 1.4.9999999.9999999-dev -> satisfiable by akeneo/pim-community-dev[1.4.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Best regards
BTW. Good job

**Comment by linslin** [comment]
Hi, I will not support this shit codes any more. Akeneo/PIM is a  peace of shit.

**Comment by rskonieczka** [comment]
Thank you for your answer, good luck.
